name: docker built and push

on:
    push: 
        tags:
            - "*"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - 
                name: checkout
                uses: actions/checkout@v3

            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2

            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            - 
                name: login to docker hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            - 
                name: buil and push docker image api
                uses: docker/build-push-action@v2
                with:
                    context: ./api
                    file: ./Dockerfile
                    builder: ${{ steps.buildx.outputs.name }}
                    push: true
                    tags: ${{ secrets.DOCKER_USERNAME }}/api
            
            - 
                name: Verify
                run: echo ${{ steps.docker_build.outputs.digest }}
