name: built

on:
  push:
    branches: [master]
    paths:
      - "!README.md"
  pull_request:
    branches: [master]
    paths:
      - "!README.md"

jobs:
  built:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    

    steps:
      - uses: action/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install unittest
      
      - name: run unittest
        run: |
          python -m unittest discover -s tests -p "*.py"

